<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Get_character_from_KeyCode</RootNamespace>
    <AssemblyName>Get_character_from_KeyCode</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <StartupObject>Get_character_from_KeyCode.Form1</StartupObject>
  </PropertyGroup>

</Project>
